### ISSUE TITLE
Annotation styling

### ISSUE THREAD

**Issue by mattsliv** [brown-ccv/redcap-image-annotator#9]
### Tasks

- [x] Hide Expand button
- [x] Pad margin for both uploaded and annotated images to fit markerjs
- [x] Limit annotation markers
- [x] Fix bottom annotation options overflow
- [x] Make text box really small when hidding it
- [x]  Fix top annotation overflow for desktop
- [x] Have image and annotation take over text area for desktop and mobile
- [x] Adjust height and width for large images
- [x] Handle styling for portrait and landscape images
- [x] Test max width values for desktop and mobile/tablet in portrait/landscape orientation

**Comment by mattsliv** [comment]
Below shows the styling on desktop for portrait and landscape images:

https://user-images.githubusercontent.com/22246473/149969148-4c6268d7-3cf0-443e-bfe4-dcdb20993c85.mov

Below shows the styling on mobile (browser emulator) for portrait and landscape images:

https://user-images.githubusercontent.com/22246473/149970061-785768bc-d72c-4044-8542-a846c674fffd.mov

**Comment by mattsliv** [comment]
Test max width values for desktop and mobile/tablet in portrait/landscape orientation

 - `max-width: max(50vw, 250px)`: 
 - `max-width: max(80vw, 250px)`:
